gce_ssh_user ="sans"
gce_ssh_pub_key_file = ".ssh/id_rsa.pub"
gcp_project = "PROJECT_ID"
gcp_region  = "us-central1"
gcp_zone    = "us-central1-a"
gcp_key_file = "accesskey/service_account.json"
